### ISSUE TITLE
Installation How-To

### ISSUE THREAD

**Issue by aschilling** [fidyeates/PyHighcharts#3]
Hi,

I am an absolute Python beginner and I tried without any success to install and use your Highcharts wrapper. I would appreciate deeply, if you could add some instructions to the manual on how to properly install your wrapper.

Thanks

Andy

**Comment by ayamahmod** [comment]
I've the same problem, tried to solve it with all suggested solutions but they all failed.

**Comment by klahnen** [comment]
The __init__.py of the file as this:
```#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
__init__.py

__init__.py Module Docstring
"""

__author__  = "Fin"

# Stdlib Imports

# Third Party Imports

# pyhighcharts Imports
from chart import *
from maps import *
from util import JS_TYPE
```


It gets fixed adding dots to the imports like this:
```# pyhighcharts Imports
from .chart import *
from .maps import *
from .util import JS_TYPE```
